services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Craigh\SimpleScrollTheme\CraighSimpleScrollTheme'

    Craigh\SimpleScrollTheme\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Craigh\SimpleScrollTheme\Menu\AdminMenu:
        tags:
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: simpleScrollThemeAdminMenu }

