master:
  page: "master.html.twig"
  block:
    positions:
      bottomnav: "bottomnav.html.twig"
home:
  page: "home.html.twig"
  block:
    positions:
      main1: "block.html.twig"
      main2: "block.html.twig"
      main3: "block.html.twig"
      main4: "block.html.twig"
admin:
  page: "admin.html.twig"
bootstrapPath: 'themes/craighsimplescroll/css/resume.css'
